{
  "kind": "Deployment",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "cn",
    "namespace": "default",
    "labels": {
      "run": "cn"
    },

  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "run": "cn"
      }
    },
    "template": {
      "metadata": {

        "labels": {
          "run": "cn"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "cn",
            "image": "harbor.edu.cn/cn202003/cn:lastest",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
      }
    }
  }
}













apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/jkc/eureka-server:2.0.4
        imagePullPolicy: IfNotPresent
        name: eureka-server
      restartPolicy: Always
